Syntax aware spellchecking
fischerling/vis-spellcheck pull request #3
Opened 2020-08-26 14:54 UTC by fischerling

## Current state
Hijacking the lexer's `lex` function and inserting our typo highlighting into the token stream works.  
The algorithm now calls the external spellchecker at most once per `lex` run which is much faster than calling it for each token we want to spellcheck. I would consider it usable but the performance could still be improved.

## TODO
- [ ]  improve list of spellchecked lexer tokens (e.g. syntax=diff needs default tokens checked to spellcheck my git commit messages)
- [ ]  maybe make the emitted token type configurable or introduce a new one (how would it get styled?)
- [ ]  test if only spellchecking the content of the tokens we want to check brings a performance advantage

It would be great if you could try it and tell me your oppinon @Mikmert ;)

2020-08-26 17:51 UTC, Mikmert commented
__Good__
It is preforming much better then the first iteration.  It has also removed a bug from the original where if you scroll or uses j so the buffer moves up or down the lexing from Vis disappear until you scroll in the opposite direction. It is working for strings and comments.

__Bad__
The spellchecking do not work for tex family documents normal text. The spell wrong color can be a little hard to see sometimes when it is the same as the syntax.
So overall it is working good, nice work.

Encounter a error when I wrote a few symbols on the first empty line in a text file.
`vis-spellcheck/spellcheck.lua:96: attempt to perform arithmetic on a nil value (local 'start')`

2020-08-26 19:41 UTC, Mikmert commented on spellcheck.lua
> +			return typo, start + 1, finish - 1
Error: start and finish can be nil value which stops the preforming of arithmetic. Should maybe be a if before to check start and finish values.

2020-08-26 19:52 UTC, Mikmert commented on spellcheck.lua
> +				if token_end < typo_start or not spellcheck.check_tokens[token_type] then
Error: The token_end and typo_start can be nil value.

2020-08-26 20:17 UTC, Mikmert commented on spellcheck.lua
> +					table.insert(new_tokens, typo_end + 1)
`attempt to perform arithmetic on a nil value (local 'typo_end')`

2020-08-26 20:21 UTC, Mikmert commented on spellcheck.lua
> +			until(not token_end or token_end >= typo_end)
Error: `attempt to compare nil with number`

2020-08-26 20:39 UTC, Mikmert requested changes
Several errors where nil is being compared.

2020-08-27 14:00 UTC, fischerling commented
Thanks for your investigation!
But I think that `token_start` and `token_end` should never be `nil` because if the typo reported from our spellchecker can't be found in the text it is definitly a bug.
819f67b78f2bc64f39fc0a48613908c36c674621 should fix this. The pattern used to find typos does not match them at the beginning or end of the text so this is now special cased.

2020-08-27 14:03 UTC, fischerling commented
e23acde adds vis.lexers.DEFAULT to the tokens we spellcheck by default this should enable spellchecking in latex or markdown.

2020-08-27 16:13 UTC, Mikmert commented
spellcheck.lua:96: attempt to perform arithmetic on a nil value (local 'start')

2020-08-27 16:35 UTC, Mikmert commented
Most of the nil bugs seems to be gone but encountered one `spellcheck.lua:83: attempt to index a nil value (local 'typos')`. The `set spelllang` do not update until you move or manipulate text probably a effect of subscribing to `vis.events.WIN_HIGHLIGHT`. Overall is it looking better.

2020-08-27 16:41 UTC, Mikmert commented
Do not seem to like big documents. The spellchecking stops working completely and do not mark anything.

2020-08-28 10:54 UTC, fischerling commented
> Most of the nil bugs seems to be gone but encountered one spellcheck.lua:83: attempt to index a nil value (local 'typos') at the same time this show up calling enchant-2 -l -d se -a failed (1).

This I think happens because "se" is not a valid dictionary description, but then we should't crash and just not highlight

2020-08-28 10:55 UTC, fischerling commented
> Do not seem to like big documents. The spellchecking stops working completely and do not mark anything.

Does vis still respond or does it hang and consume 100% CPU ?

2020-08-28 11:13 UTC, fischerling commented
> The set spelllang do not update until you move or manipulate text probably a effect of subscribing to vis.events.WIN_HIGHLIGHT

should be fixed by 96bf9b1b50c641671390ef4e9d84206c69137150.

2020-08-28 11:33 UTC, Mikmert commented
It just stops highlighting words and say something like: `typo ettext not where expected after 1798 at 1793 1798 found: ike a`. Vis is still responding.

2020-08-28 11:48 UTC, fischerling commented
> > Does vis still respond or does it hang and consume 100% CPU ?
> 
> It just stops highlighting words and say something like: `typo ettext not where expected after 1798 at 1793 1798 found: ike a`. Vis is still responding.

The outputs means that there was a typo reported by the external spellchecker "ettext" and it must be after the last typo which ended at 1798 characters in the lexed data.
But it was not found by our normal pattern `[%A]ettext[%A]` so we assume it must be the last part of the data and therefore match the following pattern `[%A]ettext$` but we found "ike a" where we expected "ettext".

Does "ettext" occur in the file you are editing?

How many windows are open in vis ?
Could you provide me with the file if it is not sensitive in any form?

2020-08-28 11:59 UTC, Mikmert commented
It is just a expel file for markdown I used for testing her you go.
[markdown.txt](https://github.com/fischerling/vis-spellcheck/files/5141905/markdown.txt)

2020-08-28 12:05 UTC, fischerling commented
> It is just a expel file for markdown I used for testing her you go.
> [markdown.txt](https://github.com/fischerling/vis-spellcheck/files/5141905/markdown.txt)
> Regarding your questions:
> 
> > Does "ettext" occur in the file you are editing?
> 
> Yes once but it is EtText in the document
> 
> > How many windows are open in vis ?
> 
> one window

Thanks for providing me the file.  
When does the highlighting break? Because I can't reproduce it by just scrolling through the file.

2020-08-28 12:20 UTC, Mikmert commented
If I just open the file in Vis and turn on spellchecker I get `can't find typo Markdown-formatted after 957. Please report this bug.` Then I get new error messages every time I scroll so the buffer moves. The first one is `can't find typo as-is after 1023. Please report this bug.`

2020-08-28 12:26 UTC, fischerling commented
> If I just open the file in Vis and turn on spellchecker I get `can't find typo Markdown-formatted after 957. Please report this bug.` Then I get new error messages every time I scroll so the buffer moves. The first one is `can't find typo as-is after 1023. Please report this bug.`

Hm interesting. What lua version are you using and do you know the size of your terminal so I can try to reproduce your viewport ?

2020-08-28 12:36 UTC, Mikmert commented
The Lua version is 5.4.0, the terminal size do not seem to matter but the latest window have this info about it `Position: 1002,49 (screen: 0) Geometry: 903x1016` have tested with other geometry. My terminal is alacritty.

2020-08-28 12:46 UTC, fischerling commented
> The Lua version is 5.4.0, the terminal size do not seem to matter but the latest window have this info about it `Position: 1002,49 (screen: 0) Geometry: 903x1016` have tested with other geometry. My terminal is alacritty.

Ok I am too using lua 5.4 so it is no weird standard library difference or something like that.
Does the highlighting deterministically crash independent of the terminal size and the position in the file?

Do you know which spelling provider you use for enchant-2?

```shell
$ enchant-lsmod-2

hunspell (Hunspell Provider)
aspell (Aspell Provider)
```
So I use hunspell by default.

2020-08-28 13:00 UTC, Mikmert commented
```enchant-lsmod-2

** (process:121751): WARNING **: 14:55:57.458: Error loading plugin: libnuspell.so.3: cannot open shared object file: No such file or directory

hunspell (Hunspell Provider)
voikko (Voikko Provider)
aspell (Aspell Provider)
hspell (Hspell Provider)
```
I get a warning. Perhaps that is what  causes the issue.

2020-08-28 13:06 UTC, fischerling commented
> ```
> enchant-lsmod-2
> 
> ** (process:121751): WARNING **: 14:55:57.458: Error loading plugin: libnuspell.so.3: cannot open shared object file: No such file or directory
> 
> hunspell (Hunspell Provider)
> voikko (Voikko Provider)
> aspell (Aspell Provider)
> hspell (Hspell Provider)
> ```
> 
> I get a warning. Perhaps that is what causes the issue.

No the warning is just that enchant can't find one of it's spellchecking providers (libnuspell for finish support).
I changed my enchant.ordering  from `hunspell,aspell` to `aspell,hunspell` and now I finally can reproduce your errors.

2020-08-28 13:25 UTC, fischerling commented
So apparently the typo lists returned by aspell differs from the one produced by hunspell not only by the detected typos but also contains a blank line which breaks our increasing typo search through the text.

Ignoring empty typos (500a12c36f8112a7b66a5e10f0733b3374e3c1f0) in the list from the external spellchecker fixes highlighting with aspell for me.

2020-08-28 13:39 UTC, Mikmert commented
The error is gone thank you. In the file I gave you markdown.txt the spellchecking stops after line 27.

2020-08-28 14:05 UTC, fischerling commented
> The error is gone thank you. In the file I gave you markdown.txt the spellchecking stops after line 27. The line with `----`. Looks like some combinations with hyphen `-` stops the spellchecking. Every misspell before is marked nothing after.

This is because I am stupid and ignored the empty typo at the wrong locations.
The current code just stops iterating typos when an empty one is encountered.

But than we have still a problem: When the typo contains characters which have special meaning for lua patterns
like '-' in 'easy-to-read' our pattern matching does all kinds of things but not finding the typo we are looking for.

2020-08-28 14:49 UTC, fischerling commented
Now the file markdown.txt you provided should be correctly spellchecked using either aspell or hunspell as enchant spelling provider.

2020-09-17 09:36 UTC, merged